export const labels = {
  en: {
    examTitle: "PMP Examination",
    questionOf: (current: number, total: number) => `Question ${current} of ${total}`,
    timeRemaining: "Time Remaining:",
    english: "English",
    arabic: "العربية",
    previous: "Previous",
    next: "Next",
    markForReview: "Mark for Review",
    unmarkForReview: "Unmark Review",
    calculator: "Calculator",
    endExam: "End Exam",
    questionReviewList: "QUESTION REVIEW LIST",
    answered: "Answered",
    current: "Current",
    markedForReview: "Marked for Review",
    endExamConfirm: "End Exam?",
    endExamMessage: (unanswered: number) =>
      unanswered > 0
        ? `You have ${unanswered} unanswered question(s). Are you sure you want to end the exam?`
        : "Are you sure you want to end the exam?",
    confirm: "Yes, End Exam",
    cancel: "Cancel",
    timeUp: "Time's Up!",
    timeUpMessage: "Your exam time has expired. Your answers have been submitted.",
    viewResults: "View Results",
    startNewExam: "Start New Exam",
    pause: "Pause",
    resume: "Resume",
    examPaused: "Exam Paused",
    examPausedMessage: "Your exam is paused. Your timer is frozen.",
    // Toolbar
    comment: "Comment",
    highlight: "Highlight",
    strikethrough: "Strikethrough",
    flagForReview: "Flag for Review",
    colorScheme: "Color Scheme",
    navigator: "Navigator",
    help: "Help",
    translate: "Translation",
    // Navigator modal
    unseen: "Unseen",
    incomplete: "Incomplete",
    flagged: "Flagged",
    comments: "Comments",
    navigatorTitle: "Navigator – select a question to go to it",
    closeNavigator: "Close",
    // Color scheme names
    colorSchemes: {
      "black-on-white": "Black on White",
      "black-on-yellow": "Black on Yellow",
      "black-on-lt-yellow": "Black on Light Yellow",
      "black-on-salmon": "Black on Salmon",
      "blue-on-white": "Blue on White",
      "blue-on-yellow": "Blue on Yellow",
      "lt-yellow-on-black": "Light Yellow on Black",
      "white-on-black": "White on Black",
      "white-on-blue": "White on Blue",
    },
    // Help modal
    helpTitle: "Exam Help",
    helpText: "Use Previous and Next to navigate between questions. Flag questions for review using the Flag button. Use the Navigator to jump to any question. You can add comments to questions and use strikethrough to eliminate answer choices.",
    // Comment modal
    commentTitle: "Comment",
    commentPlaceholder: "Type your note here...",
    commentSave: "Save",
    commentDelete: "Delete",
  },
  ar: {
    examTitle: "اختبار PMP",
    questionOf: (current: number, total: number) => `السؤال ${current} من ${total}`,
    timeRemaining: "الوقت المتبقي:",
    english: "English",
    arabic: "العربية",
    previous: "السابق",
    next: "التالي",
    markForReview: "علامة للمراجعة",
    unmarkForReview: "إزالة علامة المراجعة",
    calculator: "الآلة الحاسبة",
    endExam: "إنهاء الاختبار",
    questionReviewList: "قائمة مراجعة الأسئلة",
    answered: "تمت الإجابة",
    current: "الحالي",
    markedForReview: "مُعلَّم للمراجعة",
    endExamConfirm: "إنهاء الاختبار؟",
    endExamMessage: (unanswered: number) =>
      unanswered > 0
        ? `لديك ${unanswered} سؤال/أسئلة بدون إجابة. هل أنت متأكد من إنهاء الاختبار؟`
        : "هل أنت متأكد من إنهاء الاختبار؟",
    confirm: "نعم، أنهِ الاختبار",
    cancel: "إلغاء",
    timeUp: "انتهى الوقت!",
    timeUpMessage: "انتهى وقت الاختبار. تم إرسال إجاباتك.",
    viewResults: "عرض النتائج",
    startNewExam: "بدء اختبار جديد",
    pause: "إيقاف مؤقت",
    resume: "استئناف",
    examPaused: "الاختبار متوقف",
    examPausedMessage: "اختبارك متوقف. الوقت مجمّد.",
    // Toolbar
    comment: "تعليق",
    highlight: "تمييز",
    strikethrough: "شطب",
    flagForReview: "وضع علامة للمراجعة",
    colorScheme: "نظام الألوان",
    navigator: "متصفح الأسئلة",
    help: "مساعدة",
    translate: "ترجمة",
    // Navigator modal
    unseen: "لم يُشاهَد",
    incomplete: "غير مكتمل",
    flagged: "مُعلَّم",
    comments: "تعليقات",
    navigatorTitle: "متصفح الأسئلة – اختر سؤالاً للانتقال إليه",
    closeNavigator: "إغلاق",
    // Color scheme names
    colorSchemes: {
      "black-on-white": "أسود على أبيض",
      "black-on-yellow": "أسود على أصفر",
      "black-on-lt-yellow": "أسود على أصفر فاتح",
      "black-on-salmon": "أسود على سلموني",
      "blue-on-white": "أزرق على أبيض",
      "blue-on-yellow": "أزرق على أصفر",
      "lt-yellow-on-black": "أصفر فاتح على أسود",
      "white-on-black": "أبيض على أسود",
      "white-on-blue": "أبيض على أزرق",
    },
    // Help modal
    helpTitle: "مساعدة الاختبار",
    helpText: "استخدم السابق والتالي للتنقل بين الأسئلة. ضع علامة على الأسئلة للمراجعة باستخدام زر العلامة. استخدم المتصفح للانتقال إلى أي سؤال. يمكنك إضافة تعليقات على الأسئلة واستخدام الشطب لاستبعاد خيارات الإجابة.",
    // Comment modal
    commentTitle: "تعليق",
    commentPlaceholder: "اكتب ملاحظتك هنا...",
    commentSave: "حفظ",
    commentDelete: "حذف",
  },
};

export type Labels = typeof labels.en;
